### ISSUE TITLE
Compiler/Visual Studio Crash in switch statement (?)

### ISSUE THREAD

**Issue by lucidvizion** [nikhilk/scriptsharp#88] opened 2011-07-27 16:46 UTC
This .cs file, exactly as written, will not compile in 0.7.2:

using System;
using System.Collections.Generic;
using System.Html;
using System.Collections;

namespace ScriptLibrary1
{
    public class Class1
    {
        public void Go()
        {
            Dictionary dict = new Dictionary("Key", "Value");
            DictionaryEntry de = null;

```
        foreach(DictionaryEntry d in dict)
        {
            de = d;
        }

        Type t = typeof(String);

        string key = de.Key;

        switch (t.Name)
        {
            case "String":
                if (key == "XPath")
                    addXpathStringProp(de);
                else
                    addStringProp(de);
                break;
            case "Number":
                addEnumProp(de);
                break;
            case "Int32":
                addIntegerProp(de);
                break;
            case "Boolean":
                addBoolProp(de);
                break;
            case "Control":
                addControlProp(de);
                break;
            case "Option":
                addOptionProp(de);
                break;
            case "CssSize":
                addCssSizeProp(de);
                break;
            case "CompositeControlAlignment":
                addCompositeControlAlignmentProp(de);
                break;
            case "Section":
                addSectionProp(de);
                break;
            case "XFormsBindings":
                addXFormsBindingsProp(de);
                break;
            default:
                throw new Exception(string.Format("Missing client side logic to handle {0} property types.  Add to PropertiesController class.", t.Name));
        }                

    }

    public void addEnumProp(DictionaryEntry de) { }
    public void addIntegerProp(DictionaryEntry de) { }
    public void addBoolProp(DictionaryEntry de) { }
    public void addControlProp(DictionaryEntry de) { }
    public void addOptionProp(DictionaryEntry de) { }
    public void addStringProp(DictionaryEntry de) { }
    public void addSectionProp(DictionaryEntry de) { }
    public void addXFormsBindingsProp(DictionaryEntry de) { }
    public void addXpathStringProp(DictionaryEntry de) { }
    public void addCssSizeProp(DictionaryEntry de) { }
    public void addCompositeControlAlignmentProp(DictionaryEntry de) { }
}
```

}

If I comment out any 5 of the case statements like so, it will compile:

switch (t.Name)
            {
                case "String":
                    if (key == "XPath")
                        addXpathStringProp(de);
                    else
                        addStringProp(de);
                    break;
                case "Number":
                    addEnumProp(de);
                    break;
                case "Int32":
                    addIntegerProp(de);
                    break;
                case "Boolean":
                    addBoolProp(de);
                    break;
                case "Control":
                    addControlProp(de);
                    break;
                //case "Option":
                //    addOptionProp(de);
                //    break;
                //case "CssSize":
                //    addCssSizeProp(de);
                //    break;
                //case "CompositeControlAlignment":
                //    addCompositeControlAlignmentProp(de);
                //    break;
                //case "Section":
                //    addSectionProp(de);
                //    break;
                //case "XFormsBindings":
                //    addXFormsBindingsProp(de);
                //    break;
                default:
                    throw new Exception(string.Format("Missing client side logic to handle {0} property types.  Add to PropertiesController class.", t.Name));
 }                

Build Errors:
Error   1   Internal Compiler Error: stage 'BEGIN'  ScriptLibrary1
Error   2   Internal Compiler Error: stage 'EMIT'   ScriptLibrary1
Error   3   Internal Compiler Error: stage 'COMPILE'    ScriptLibrary1
Error   4   Internal Compiler Error: stage 'COMPILE'    C:\Users\Documents\Visual Studio 2010\Projects\ScriptLibrary1\ScriptLibrary1\Class1.cs ScriptLibrary1
Error   5   Internal Compiler Error: stage 'COMPILE' symbol '<global namespace>'    C:\Users\Documents\Visual Studio 2010\Projects\ScriptLibrary1\ScriptLibrary1\Class1.cs ScriptLibrary1
Error   6   Internal Compiler Error: stage 'CODEGEN'    C:\Users\Documents\Visual Studio 2010\Projects\ScriptLibrary1\ScriptLibrary1\Class1.cs ScriptLibrary1
Error   7   Internal Compiler Error (0xc0000005 at address 5D03C3C9): likely culprit is 'CODEGEN'.

An internal error has occurred in the compiler. To work around this problem, try simplifying or changing the program near the locations listed below. Locations at the top of the list are closer to the point at which the internal error occurred. Errors such as this can be reported to Microsoft by using the /errorreport option.
    ScriptLibrary1
Error   8   Internal Compiler Error: stage 'COMPILE' symbol 'ScriptLibrary1'    C:\Users\Documents\Visual Studio 2010\Projects\ScriptLibrary1\ScriptLibrary1\Class1.cs 7   11  ScriptLibrary1
Error   9   Internal Compiler Error: stage 'COMPILE' symbol 'ScriptLibrary1.Class1' C:\Users\Documents\Visual Studio 2010\Projects\ScriptLibrary1\ScriptLibrary1\Class1.cs 9   18  ScriptLibrary1
Error   10  Internal Compiler Error: stage 'COMPILE' symbol 'ScriptLibrary1.Class1.Go()'    C:\Users\Documents\Visual Studio 2010\Projects\ScriptLibrary1\ScriptLibrary1\Class1.cs 11  21  ScriptLibrary1
Error   11  Internal Compiler Error: stage 'COMPILE' symbol 'ScriptLibrary1.Class1.Go()'    C:\Users\Documents\Visual Studio 2010\Projects\ScriptLibrary1\ScriptLibrary1\Class1.cs 11  21  ScriptLibrary1
Error   12  Internal Compiler Error: stage 'CODEGEN' symbol 'ScriptLibrary1.Class1.Go()'    C:\Users\Documents\Visual Studio 2010\Projects\ScriptLibrary1\ScriptLibrary1\Class1.cs 11  21  ScriptLibrary1
Error   13  Internal Compiler Error: stage 'CODEGEN'    C:\Users\Documents\Visual Studio 2010\Projects\ScriptLibrary1\ScriptLibrary1\Class1.cs 25  13  ScriptLibrary1

**Comment by lucidvizion** [comment] 2011-07-27 16:48
I forgot to add that this worked fine in 0.6.3

**Comment by nikhilk** [comment] 2011-08-07 01:43
Duplicate of https://github.com/nikhilk/scriptsharp/issues/56

**Closed as completed by nikhilk** 2011-08-07 01:43 UTC
