### ISSUE TITLE
C# (x == null) statement compiled to JS returns true when x=0

### ISSUE THREAD

**Issue by vgribok** [nikhilk/scriptsharp#51] opened 2011-05-16 16:00 UTC
Script# compiles C# if(x == null) into JS if(!x), which returns true when x=0, which is a huge problem for people coming from C# background, so I hope it's not by design. I can see S# compiling x==null into JS (x == null || x==undefined), which would be much more intuitive for devs transitioning from C# wold into JS world. I realize this can be worked around using Script.IsNull() or Script.IsNullOrUndefined(), but the fact remains that x==null in regular C# would not evaluate to true if x was a number, and S# should follow the same path.

**Comment by nikhilk** [comment] 2011-05-16 16:06
Duplicate of #31.
Will be changing generation of if (x == null) back to if (x == null) in generated script.

**Closed as completed by nikhilk** 2011-05-16 16:06 UTC
