### ISSUE TITLE
Firefox/IE/Chrome rendering diffference

### ISSUE THREAD

**Issue by MarkStega** [nikhilk/scriptsharp#408] opened 2013-11-19 19:43 UTC
I am looking for a bit of advice. I built the KOWorld demo and it worked. I then set my sights on Todo and had odd behavior in Chrom. I am not looking for a solution, but instead, how one approaches this kind of issue in the Script#/jQuery world.

Chrome (2nd item has been checked as complete, text went from '456' to 'on'; no check persists; 'Clear completed' button does not appear)
![image](https://f.cloud.github.com/assets/634561/1575757/49241464-5152-11e3-8315-fa8a2200910e.png)

Firefox: (1st item checked):
![image](https://f.cloud.github.com/assets/634561/1575775/8b509218-5152-11e3-8f8d-1fd46b2b192a.png)

IE: Essentially the same as FF

**Comment by theoutlander** [comment] 2013-11-19 21:24
I would start by debugging the JavaScript in the chrome debugger and then in the ie/ff debugger and try to see where things are different. I don't have the project handy to try it and I'm not exactly clear from the screenshots as to where the issue is. It could also be as simple as a CSS issue.

Sent from my Windows Phone

**Comment by nikhilk** [comment] 2013-11-24 17:51
In general, the debugging story for script# generated scripts should be the same as debugging hand-authored script.

I'll close this out as it seems to be a general question, but if you do find a bug in the sample, please help fix it/re-open this with the result of investigation as a sample issue.

**Closed as completed by nikhilk** 2013-11-24 17:51 UTC
