### ISSUE TITLE
VS 2012

### ISSUE THREAD

**Issue by Lightw3ight** [nikhilk/scriptsharp#212] opened 2012-07-25 08:40 UTC
This isn't a bug/issue per say, i'm just after some information.

Is is possible to install Script# for VS 2012 RC 
If the answer to the above question is yes, has anyone started writing any import libraries for the metro javascript classes?

**Comment by nikhilk** [comment] 2012-07-25 14:36
0.7.4 doesn't install templates into VS2012.

However, with all the recent changes I committed, what comes out of the build is a vsix that does load into VS2012 RC. I've been using it in there on my end.

So given that, I'd love to see import assemblies defined for the new metro apps. I'd like to see two assemblies - first a Script.WinRT.dll with the Windows.\* APIs and then a different Script.WinJS.dll for the WinJS.\* APIs. It would be great to see some collaboration on this...

**Comment by Lightw3ight** [comment] 2012-07-30 03:01
I tried pulling down the source to build and get the visx file to use in 2012 but i got several build errors and eventually gave in as it looks like you're quite close to a 0.7.5 release.
As for the import libraries, im more than happy to kick them off when im able to use 2012

-Kris

**Comment by nikhilk** [comment] 2012-07-30 04:11
I have added the 0.7.5 vsix to the downloads section at https://github.com/nikhilk/scriptsharp/downloads. I need to put this up into the VS extension gallery, but its not working for me right now. The vsix primarily contains project and item templates. It should install into VS2012, VS2010 and express editions of VC# and Visual Web Developer. The templates make use of nuget packages for msbuild integration, the core libraries, all the import libraries and runtime scripts. See http://nuget.org/packages?q=scriptsharp.

Once you install the vsix (simply double click) you should be set - you'll see templates under Script# within Visual C# in the Add Project folder inside VS.

You'll likely need to uninstall the existing 0.7.4 build so templates do not conflict.

Hopefully this will get you going. Please do try and let me know how this stuff goes. Need real-world testing to get beyond the "it works on my machine" situation. :-)

**Comment by michaelaird** [comment] 2012-07-30 18:03
The current vsix installed happily to VS2012 but did not find VS2010 for me....do i need to do something special? runas admin?

**Comment by nikhilk** [comment] 2012-07-30 21:45
Odd - the vsix manifest lists v10 as the required version. https://github.com/nikhilk/scriptsharp/blob/master/src/ZipX/VSIX/Extension.vsixmanifest. Perhaps I missed something there...

**Comment by michaelaird** [comment] 2012-07-30 22:08
I have the Premium version of 2012 but the Ultimate version of 2010. I wonder if the vsix installer stops once it matches one sku/version...

**Comment by nikhilk** [comment] 2012-07-31 01:29
Don't really know intended behavior, but I thought it was to prompt for every installed product. At least that is what the list in the vsix is supposed to enable.

**Comment by dealproc** [comment] 2012-08-03 23:56
Hmm... tried to download/install 0.7.5 and got an error "The extension manifest is invalid." for VS2010 Professional.

**Comment by dealproc** [comment] 2012-08-04 00:07
I downloaded http://visualstudiogallery.msdn.microsoft.com/e3d76792-d1b3-4d0c-9716-1f16c38be8b3/ and when I tried to look at the Xml in the window, it's saying that the extension manifest could not be loaded: There is an error in XML document (1,2). <PackageManifest xmlns='http://schemas.microsoft.com/developer...'> was not expected.

**Comment by nikhilk** [comment] 2012-08-04 02:47
Any chance there was more information about the error that might help understand?

I tried downloading the extension, and unfortunately I can't install the vsix explorer extension itself to run myself since it doesn't seem to install into VS2012, and I don't have VS2010 anymore. Ironic...

**Comment by michaelaird** [comment] 2012-08-04 12:28
I did a bit of research and it looks like they changed the package manifest schema between 2010 and 2012.

I "backported" the manifest to the V1 schema and tested it locally and it works with 2010 now.

here you go:

```
<?xml version="1.0" encoding="utf-8"?>
<Vsix xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Version="1.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2010">
  <Identifier Id="ScriptSharp.Extension.Templates">
    <Name>Script#</Name>
    <Author>Nikhil Kothari</Author>
    <Version>0.7.5</Version>
    <Description xml:space="preserve">Script# lets you author your HTML5 apps in C# and compile them into JavaScript.</Description>
    <Locale>1033</Locale>
    <MoreInfoUrl>http://www.scriptsharp.com/</MoreInfoUrl>
    <License>License.txt</License>
    <Icon>Logo.png</Icon>
    <PreviewImage>Logo.png</PreviewImage>
    <SupportedProducts>
      <VisualStudio Version="10.0">
        <Edition>Ultimate</Edition>
        <Edition>Premium</Edition>
        <Edition>Pro</Edition>
        <Edition>VBExpress</Edition>
        <Edition>VCSExpress</Edition>
        <Edition>VWDExpress</Edition>
      </VisualStudio>
      <VisualStudio Version="11.0">
        <Edition>Ultimate</Edition>
        <Edition>Premium</Edition>
        <Edition>Pro</Edition>
        <Edition>VBExpress</Edition>
        <Edition>VCSExpress</Edition>
        <Edition>VWDExpress</Edition>
      </VisualStudio>
    </SupportedProducts>
    <SupportedFrameworkRuntimeEdition MinVersion="4.0" MaxVersion="4.0" />
    <AllUsers>true</AllUsers>
  </Identifier>
  <References>
    <Reference Id="Microsoft.Framework.NDP" MinVersion="4.0" >
      <Name>Microsoft .NET Framework</Name>
    </Reference>
    <Reference Id="NuPackToolsVsix.Microsoft.67e54e40-0ae3-42c5-a949-fddf5739e7a5" MinVersion="2.0" >
      <Name>NuGet Package Manager</Name>
    </Reference>
  </References>
  <Content>
    <ProjectTemplate>ProjectTemplates\ClassLibrary</ProjectTemplate>
    <ProjectTemplate>ProjectTemplates\ImportLibrary</ProjectTemplate>
    <ProjectTemplate>ProjectTemplates\jQueryClassLibrary</ProjectTemplate>
    <ProjectTemplate>ProjectTemplates\UnitTest</ProjectTemplate>
    <ItemTemplate>ItemTemplates\Class</ItemTemplate>
    <ItemTemplate>ItemTemplates\jQueryPage</ItemTemplate>
    <ItemTemplate>ItemTemplates\jQueryPlugin</ItemTemplate>
    <ItemTemplate>ItemTemplates\Page</ItemTemplate>
    <ItemTemplate>ItemTemplates\Resource</ItemTemplate>
    <ItemTemplate>ItemTemplates\TestClass</ItemTemplate>
  </Content>
</Vsix>

```

**Comment by dealproc** [comment] 2012-08-04 19:28
Hey... thx. man.  I'll try that out as soon as my burn of Win8 RC is done.  I figured last resort was loading Win8 on a test machine and get VS.NET 2012 pro running.  seems like there is supposed to be some tooling available in 2012 that will be better anyhow for developing web rich client apps in HTML5 type fashion.

**Comment by dealproc** [comment] 2012-08-04 19:29
@nikhilk what I told you in the error message is exactly what I got on screen.

**Comment by dealproc** [comment] 2012-08-04 20:52
so I copied and pasted @michaelaird code from above into the project, compiled, and got this:

<pre>
8/4/2012 4:50:13 PM - Microsoft Visual Studio Extension Installer
8/4/2012 4:50:13 PM - -------------------------------------------
8/4/2012 4:50:13 PM - Initializing Install...
8/4/2012 4:50:13 PM - Extension Details...
8/4/2012 4:50:13 PM -   Identifier      : ScriptSharp.Extension.Templates
8/4/2012 4:50:13 PM -   Name            : Script#
8/4/2012 4:50:13 PM -   Author          : Nikhil Kothari
8/4/2012 4:50:13 PM -   Version         : 0.7.5
8/4/2012 4:50:13 PM -   Description     : Script# lets you author your HTML5 apps in C# and compile them into JavaScript.
8/4/2012 4:50:13 PM -   Locale          : en-US
8/4/2012 4:50:13 PM -   MoreInfoURL     : http://www.scriptsharp.com/
8/4/2012 4:50:13 PM -   InstalledByMSI  : False
8/4/2012 4:50:13 PM -   MinFramework    : 4.0
8/4/2012 4:50:13 PM -   MaxFramework    : 4.0
8/4/2012 4:50:13 PM - 
8/4/2012 4:50:13 PM -   Supported Visual Studio Editions : 
8/4/2012 4:50:13 PM -       Version : 10.0
8/4/2012 4:50:13 PM -           Ultimate
8/4/2012 4:50:13 PM -           Premium
8/4/2012 4:50:13 PM -           Pro
8/4/2012 4:50:13 PM -           VBExpress
8/4/2012 4:50:13 PM -           VCSExpress
8/4/2012 4:50:13 PM -           VWDExpress
8/4/2012 4:50:13 PM -       Version : 11.0
8/4/2012 4:50:13 PM -           Ultimate
8/4/2012 4:50:13 PM -           Premium
8/4/2012 4:50:13 PM -           Pro
8/4/2012 4:50:13 PM -           VBExpress
8/4/2012 4:50:13 PM -           VCSExpress
8/4/2012 4:50:13 PM -           VWDExpress
8/4/2012 4:50:13 PM - 
8/4/2012 4:50:13 PM -   Supported Isolated Shells : 
8/4/2012 4:50:13 PM - 
8/4/2012 4:50:13 PM -   References      : 
8/4/2012 4:50:13 PM -       -------------------------------------------------------
8/4/2012 4:50:13 PM -       Identifier   : Microsoft.Framework.NDP
8/4/2012 4:50:13 PM -       Name         : Microsoft .NET Framework
8/4/2012 4:50:13 PM -       MinVersion   : 4.0
8/4/2012 4:50:13 PM -       MaxVersion   : 
8/4/2012 4:50:13 PM -       MoreInfoURL  : 
8/4/2012 4:50:13 PM -       Nested       : No
8/4/2012 4:50:13 PM - 
8/4/2012 4:50:13 PM -       -------------------------------------------------------
8/4/2012 4:50:13 PM -       Identifier   : NuPackToolsVsix.Microsoft.67e54e40-0ae3-42c5-a949-fddf5739e7a5
8/4/2012 4:50:13 PM -       Name         : NuGet Package Manager
8/4/2012 4:50:13 PM -       MinVersion   : 2.0
8/4/2012 4:50:13 PM -       MaxVersion   : 
8/4/2012 4:50:13 PM -       MoreInfoURL  : 
8/4/2012 4:50:13 PM -       Nested       : No
8/4/2012 4:50:13 PM - 
8/4/2012 4:50:13 PM - 
8/4/2012 4:50:13 PM - Searching for applicable products...
8/4/2012 4:50:13 PM - Found installed product - Microsoft Visual Studio 2010 Professional
8/4/2012 4:50:13 PM - The extension with ID 'ScriptSharp.Extension.Templates' is not installed to Microsoft Visual Studio 2010 Professional.
8/4/2012 4:50:22 PM - The following target products have been selected...
8/4/2012 4:50:22 PM -   Microsoft Visual Studio 2010 Professional
8/4/2012 4:50:22 PM - 
8/4/2012 4:50:22 PM - Beginning to install extension to Microsoft Visual Studio 2010 Professional...
8/4/2012 4:50:22 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Microsoft .NET Framework
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
</pre>

**Comment by nikhilk** [comment] 2012-08-04 22:50
I am assuming you do have .net 4.0 installed, and this is unexpected error. If so, perhaps we can simply leave out the Microsoft.Framework.NDP reference from the list... since it is covered by requiring VS2010/VS2012. Can you try with that change, and report back?

@michaelaird ... I tried your version, and that didn't seem to work for me with VS2012. When I tried to install the resulting package, I didn't see the templates, even though there were no errors.

OK, did some more trial and error, and the following works in 2012 ... if you could try on VS2010 again, that would be good.

```
<?xml version="1.0" encoding="utf-8"?>
<Vsix
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://schemas.microsoft.com/developer/vsx-schema/2010"
  Version="1.0.0">
  <Identifier Id="ScriptSharp.Extension.Templates">
    <Name>Script#</Name>
    <Author>Nikhil Kothari</Author>
    <Version>0.7.5</Version>
    <Description xml:space="preserve">Script# lets you author your HTML5 apps in C# and compile them into JavaScript.</Description>
    <Locale>1033</Locale>
    <MoreInfoUrl>http://www.scriptsharp.com/</MoreInfoUrl>
    <License>License.txt</License>
    <Icon>Logo.png</Icon>
    <PreviewImage>Logo.png</PreviewImage>
    <SupportedProducts>
      <VisualStudio Version="10.0">
        <Edition>Ultimate</Edition>
        <Edition>Premium</Edition>
        <Edition>Pro</Edition>
        <Edition>VCSExpress</Edition>
        <Edition>VWDExpress</Edition>
      </VisualStudio>
      <VisualStudio Version="11.0">
        <Edition>Ultimate</Edition>
        <Edition>Premium</Edition>
        <Edition>Pro</Edition>
        <Edition>VCSExpress</Edition>
        <Edition>VWDExpress</Edition>
      </VisualStudio>
    </SupportedProducts>
    <SupportedFrameworkRuntimeEdition MinVersion="4.0" MaxVersion="4.0" />
  </Identifier>
  <References>
    <Reference Id="NuPackToolsVsix.Microsoft.67e54e40-0ae3-42c5-a949-fddf5739e7a5" MinVersion="2.0" >
      <Name>NuGet Package Manager</Name>
    </Reference>
  </References>
  <Content>
    <ProjectTemplate>ProjectTemplates</ProjectTemplate>
    <ItemTemplate>ItemTemplates</ItemTemplate>
  </Content>
</Vsix>
```

**Comment by michaelaird** [comment] 2012-08-06 11:53
I just tested v0.7.5.1 vsix that you posted in downloads and it works perfectly for 2010 and 2012.

**Closed as completed** 2012-08-27 06:26 UTC

**Comment by SaktiEricsson** [comment] 2014-01-18 13:45
Hi Nikhil,

  I am simply trying to add a resource file to my Script # solution and its throwing me many compilation error. How to do that? It is not able to identify many assemblies.
