### ISSUE TITLE
Using Fully Qualified name instead of using statement causes build failure

### ISSUE THREAD

**Issue by ricklove** [nikhilk/scriptsharp#102] opened 2011-09-08 16:45 UTC
namespace Root
{
  public class A
  {
    public void CauseABuildFailureWithNoErrorMessageSometimes()
    {
      // In a more complex project, this did not indicate any error (only a build failure)
      // But in this example, it at least indicates the line where the problem occurs
      Inner.B.HaveFunTryingToTrackThisDown();
    }
  }
}

namespace Root.Inner
{
  public class B
  {
    public static void HaveFunTryingToTrackThisDown()
    {
    }
  }
}

**Comment by nikhilk** [comment] 2011-09-09 02:19
Duplicate of issue #18.
This is a known issue, and will be taken care of with a larger feature work planned for script#.

**Closed as completed by nikhilk** 2011-09-09 02:19 UTC
