### ISSUE TITLE
reverse js into c#

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#147] opened 2012-02-21 15:04 UTC
Hi Nikhil,

Wondering if you ever came across a tool for reverse engineering js script files into c# import librarys for use with Script#. Probably not but I thought I'd ask.

Thanks

Donal

**Comment by CharlesMartel** [comment] 2012-02-21 15:05
I would absolutely LOVE to see this functionality. That would settle it for me and I would go script# entirely.

I considered writing a simple parser that would gather all of the class names and members in a js file and rewrite some rudimentary c# code from it. Handling the lack of strong typing in js is about where I stopped that thought experiment. 

Maybe instead a program that simply scrolls through the file asking the user to provide information about each method and class and property, and then compiles the c# code afterward. Hm... just some thoughts.

**Comment by nikhilk** [comment] 2012-02-21 17:30
There are bits and pieces of this type of functionality, but nothing specific I've seen.

What is needed is not just a basic parser, but rather a more full-fledged inference system, that infers types based on return values of known APIs being called, and how those values are passed along, and finding the best match, i.e. best probability, rather than exact match.

From my experience, the job doesn't stop there. You also have to look at what is the best way to map an API back to c#. For example, some of the jQuery APIs end up in a static jQuery class, and some end up as instance methods on a jQueryObject class. Parsing and/or reflecting on script objects alone will not give you that end-result. There is a bit of human judgement and experimentation involved to make the resulting import library optimal.

To complicate matters, every hand-written script typically varies in patterns from the next script. This rises from the flexibility of javascript, which is nice for individual script authors, but IMO presents a cost to someone who has to consume multiple scripts, and potentially understand them all, along with their subtle nuances and variations. This requirement becomes really critical the moment you want to write a general purpose automated tool.

If someone is up for building such a thing, that would be a nice contribution. I agree it would be interesting. The problem is the prospect of building and evolving such a feature is always more costly than importing any one script that is often the task at hand.

**Comment by dmcweeney** [comment] 2012-02-21 22:22
I hear ya... definitely alot more complicated that what first appears.

One starting point I would be happy to have is the ability to reverse js classes generated by Script# - the particular case in mind is the SharePoint JavaScript class library (http://msdn.microsoft.com/en-us/library/ee538253.aspx) which is written using Script#. It would be nice if they released the Dlls as import librarys but they wont.

Thanks for the thoughts...

Donal

**Comment by nikhilk** [comment] 2012-02-22 08:40
You should send feedback to folks like them ... directly and publicly. Perhaps that will help add a +1 on that, and sway things in favor of helping the ecosystem use the tools they've themselves used.

**Comment by nikhilk** [comment] 2012-05-26 06:26
Out of scope for now...

**Closed as completed by nikhilk** 2012-05-26 06:26 UTC
